#!/usr/bin/env bash
# SessionStart hook — TOOLS CARD for the niagara5-research project.
# Emits additionalContext with the LOCATION and usage of every local tool:
# the decompiled code (organized/), the ported N4 corpus-nav tools, and the
# two NEW N5-specific tools (n5-modules.py, n5-api-diff.py). Complements the
# PROTOCOL hook (n5-research-protocol.sh); this is the card for "where does
# each thing live and how do I call it".
#
# LOCATION: lives in tools/hooks/ (not .claude/, which is gitignored here) and
# is referenced from .claude/settings.json via $CLAUDE_PROJECT_DIR/tools/hooks/,
# so both pieces travel with the repo.

set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  printf 'degraded: jq missing — install jq for the tools card context\n' >&2
  printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"[degraded: jq missing — install jq for the tools card context]"}}'
  exit 0
fi

read -r -d '' CTX <<'EOF' || true
NIAGARA5-RESEARCH TOOLS — where everything lives and how to call it

All paths below are absolute and verified against this machine's N5/N4
installs. Do NOT re-decompile or re-download what is already here.

────────────────────────────────────────────────────────────────────────
0. READ-ONLY SOURCE LOCATIONS (never write here)
────────────────────────────────────────────────────────────────────────
  N5 modules (jars, one per module, schemaVersion="5"):
    /mnt/c/ProgramData/Niagara/tridium/config/5.0.0.28/modules   (247 jars)
  N5 install (bin/jre/defaults/javadoc/etc.m2):
    "/mnt/c/Program Files/Niagara/5.0.0.28"
  N4 modules (1013 jars, -rt/-ux/-wb/-se/-doc split):
    /mnt/c/Honeywell/OptimizerSupervisor-N4.14.0.162/modules
  N4 corpus (sibling repo, N4↔N5 delta baseline; docSource originals live
  under its organized/docSource/docSource-doc/extracted/):
    /home/cristian/niagara-research

────────────────────────────────────────────────────────────────────────
1. organized/ — decompiled N5 module output (source 3 of the protocol)
────────────────────────────────────────────────────────────────────────
  Root: <repo>/organized/<module>/{extracted,resources,<decompiler>,recon.json}
  Populated incrementally by tools/n5-decompile.sh — may be PARTIAL. See
  docs/decompiler-bakeoff.md for which decompiler this corpus prefers.

────────────────────────────────────────────────────────────────────────
2. Ported corpus-navigation tools (adapted from niagara-research/tools)
────────────────────────────────────────────────────────────────────────
  corpus-nav.py <find|grep|show|list|by-marker|by-focus|connections|stats>
    Navigates niagara5-block*.md + CATALOG.md + docs/ + retros/.
  gen-catalog.py
    Regenerates CATALOG.md from niagara5-block*.md. AUTOGENERATED — never
    hand-edit CATALOG.md.
  check-coverage.py <name>...
    Prior-coverage GATE before opening a new focus/gap — run on REAL module/
    package names. Scans niagara5-block*.md AND RESEARCH-STATE*.md.
  module-find.py <root> <slots|actions|writers|extends|ords|grep>
    Structural finder over a Java SOURCE tree (needs real .java — SOURCE-
    retention annotations like @NiagaraProperty do not survive decompilation).
  bog-nav.py <bog-or-xml> <tree|types|slot|find|links|handle|writable|grep|diff>
    Navigates a station config.bog or a bare file.xml (same BOG-XML grammar
    N4 uses). Verified against N5's defaults/platform.bog: parses without
    error, but that file has no h= (handle) attributes (a template default,
    not a station export) — tree/types report 0 components on it. See
    tools/README.md for the finding.
  dashboard-preview.py --rc <path> --prefix <mount>
    Local preview server for a dashboard (-ux) module's rc/ folder.
  obix-nav.py --base <url> --pass-file <path> <map|cond|wiring|config|read|dump>
    Facade<->rt auditor over oBIX Batch reads. --base/--pass-file are
    REQUIRED (no PANCCADIA default — point it at whatever N5 target station
    you are actually auditing).
  niagara-security-audit.py <niagara_home> [--station <config.bog>] [--host H]
    Station/platform security-posture checklist (SEC-01..SEC-18). Reports an
    explicit NOTFOUND row (never a silent gap or a false PASS) when its
    target path does not exist — the common case on a fresh N5 install with
    no station created yet.

────────────────────────────────────────────────────────────────────────
3. NEW N5-specific tools
────────────────────────────────────────────────────────────────────────
  n5-modules.py [--modules-dir DIR] <list|diff-n4|deps|show> [--json|--csv]
    Inventory of the N5 module set: module.xml metadata + dependency list +
    a heuristic runtime-profile hint (rt/ux/wb/px/se package-segment count,
    since N5 ships one jar per module with no profile split) + JPMS
    requires/exports (tools/lib/moduleinfo.py — pure Python, no `javap`
    dependency). `diff-n4` collapses N4's -rt/-ux/-wb/-se/-doc split back to
    base module names and reports added/removed/common vs the N5 set.
  n5-api-diff.py source [--map OLD=NEW ...] [--no-default-map] [--json]
    Source-level API diff between N4's docSource-doc/extracted/ (javax.baja.*)
    and N5's docSource.jar (niagara.*). Package-rename aware: default rule
    javax.baja.<x> -> niagara.<x> (niagara5-block3.md B3-G2); a package that
    only matches through the mapping is reported RENAMED with member deltas,
    not removed+added. Lightweight regex-based method-signature extraction —
    see the tool's docstring for documented parsing limits.
  n5-api-diff.py binary --old-jar J1 [--old-jar J2 ...] --new-jar J [--json]
    Real bytecode-level diff via japicmp 0.26.2. Needs:
      tools/decompilers/japicmp-0.26.2-jar-with-dependencies.jar
        (gitignored — download URL + sha256 in tools/README.md; NOT fetched
        automatically by the tool)
      java: /home/linuxbrew/.linuxbrew/opt/openjdk@26/bin/java (default;
        override with --java). Verified against Java 25-compiled N5
        classfiles — japicmp reads them fine.
    Multiple --old-jar flags are joined with ';' (e.g. an N4 module's
    -rt/-ux/-wb parts vs one N5 jar). No package-rename awareness (raw
    bytecode diff) — use `source` mode for a rename-aware comparison.

Run any tool with -h/--help for its full flag list before guessing one.
EOF

jq -n --arg ctx "$CTX" \
  '{hookSpecificOutput: {hookEventName: "SessionStart", additionalContext: $ctx}}'
