#!/usr/bin/env python3
"""
corpus-nav.py — Navigate the niagara5-research knowledge corpus.

Ported from niagara-research (N4 kit tool) for the niagara5-research corpus.
Adaptation from the N4 original: block filenames/H1s are English
`niagara5-block<N>.md` ("Block N") instead of Spanish
`niagara-mental-model-bloque<N>.md` ("Bloque N"); there is no consolidated
"1-3" snapshot file (N5 blocks are written one-per-file from the start); and
cross-references only use the English `[Block N]` / `[BN]` forms.

Python 3 stdlib ONLY. Deterministic, sorted output. No external deps, no DB.

The corpus (all paths relative to the repo root, resolved from this script):
  - Blocks:  niagara5-block<N>.md  (N is a GLOBAL block number with possible
             historical gaps), plus niagara5-block-test-infrastructure.md
             (label "TI").
  - CATALOG.md — AUTOGENERATED authoritative index. Each row is
             `| <label> | [file](file) | <title> |`. Source of truth for the
             block <-> title map. This tool NEVER edits it.
  - docs/*.md    — synthesis guides.
  - retros/*.md  — retrospectives.
  - RESEARCH-STATE-<focus>.md — per-focus state files.

Subcommands:
  find <query>        full-text (case-insensitive substring) search
  grep <regex>        regex search (re module)
  show <N>            H1 + section outline + Connections of block B<N>
  list                all blocks as `B<N> · <title>` (from CATALOG.md)
  by-marker <marker>  blocks containing an evidence marker (INFER, CERT-hw, ...)
  by-focus <focus>    blocks belonging to a focus (see heuristic below)
  connections <N>     forward + reverse block links for B<N>
  stats               corpus totals + marker counts

Run `corpus-nav.py <cmd> -h` for per-command flags.
"""

from __future__ import annotations

import argparse
import math
import re
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Shared search core (tools/lib/textsearch.py).
# Insert lib/ onto sys.path so the import works regardless of cwd.
# ---------------------------------------------------------------------------
sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))
import textsearch  # noqa: E402 (must follow sys.path mutation)

# ---------------------------------------------------------------------------
# Repository layout — always relative to this script's location.
# tools/corpus-nav.py  ->  repo root is the parent of tools/.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "CATALOG.md"
DOCS_DIR = REPO_ROOT / "docs"
RETROS_DIR = REPO_ROOT / "retros"

# Snapshot block files excluded from the active corpus (mirrors gen-catalog.py).
# None in the N5 corpus yet; kept as a set so the mechanism still works if one
# is ever added.
SNAPSHOTS: set[str] = set()

# ---------------------------------------------------------------------------
# Evidence markers: [CERT], [CERT-hw], [CERT-live], [CERT-doc], [CERT-web],
# [INFER], and combined forms like [CERT-doc/INFER]. A bracket token may hold
# several slash-separated components; each component is one marker instance.
# ---------------------------------------------------------------------------
_MARKER_TOKEN_RE = re.compile(r"\[((?:CERT|INFER)[\w/-]*)\]")

# ---------------------------------------------------------------------------
# Block references used inside prose / Connections. N5 corpus artifacts are
# English-only (repo-wide contract), so only the English forms are matched:
# [Block N] (dominant) and [BN]. The N4 tool's Spanish "Bloque"/"bloqueN"
# forms do not apply here.
# ---------------------------------------------------------------------------
_REF_RE = re.compile(
    r"\[Block\s+#?(\d+)\]"  # [Block 18]
    r"|\[B(\d+)\]",          # [B722]
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Block file discovery + numbering (robust to historical gaps: nothing here
# assumes N is contiguous — we only ever use the labels we actually find).
# ---------------------------------------------------------------------------
_BLOCK_NUM_RE = re.compile(r"^niagara5-block(\d+)\.md$")


def block_label_for_file(name: str) -> str | None:
    """Return the block label for a corpus filename, or None if not a block.

    Numeric blocks -> str(N); TI file -> "TI".
    """
    if name in SNAPSHOTS:
        return None
    if name == "niagara5-block-test-infrastructure.md":
        return "TI"
    m = _BLOCK_NUM_RE.match(name)
    if m:
        return str(int(m.group(1)))
    return None


def label_sort_key(label: str) -> tuple[int, int]:
    """Deterministic ordering: numeric by value, TI last."""
    if label == "TI":
        return (2, 0)
    return (1, int(label))


def display_id(label: str) -> str:
    """Human id used throughout output: B720, B1-3, BTI."""
    return f"B{label}"


def iter_block_files() -> list[tuple[str, Path]]:
    """All active block files as (label, path), sorted deterministically."""
    out: list[tuple[str, Path]] = []
    for path in REPO_ROOT.glob("niagara5-block*.md"):
        label = block_label_for_file(path.name)
        if label is not None:
            out.append((label, path))
    out.sort(key=lambda t: label_sort_key(t[0]))
    return out


def iter_dir_files(directory: Path) -> list[Path]:
    """Sorted *.md files directly under a directory (docs/, retros/)."""
    if not directory.is_dir():
        return []
    return sorted(directory.glob("*.md"))


# ---------------------------------------------------------------------------
# CATALOG.md parsing — source of truth for label -> title.
# Rows look like: `| 720 | [file](file) | title |`
# ---------------------------------------------------------------------------
_CATALOG_ROW_RE = re.compile(r"^\|\s*([^|]+?)\s*\|\s*\[[^\]]+\]\([^)]+\)\s*\|\s*(.*?)\s*\|\s*$")


def load_catalog() -> dict[str, str]:
    """Parse CATALOG.md into {label: title}. Empty dict if file is missing."""
    titles: dict[str, str] = {}
    if not CATALOG_PATH.is_file():
        return titles
    for line in CATALOG_PATH.read_text(encoding="utf-8").splitlines():
        m = _CATALOG_ROW_RE.match(line)
        if not m:
            continue
        label, title = m.group(1).strip(), m.group(2).strip()
        # Skip the header separator / header row.
        if label in ("Block", "--------") or set(label) <= {"-"}:
            continue
        titles[label] = title
    return titles


# ---------------------------------------------------------------------------
# Per-block text helpers
# ---------------------------------------------------------------------------
def read_h1(path: Path) -> str:
    """First H1 line ('# ...') from a file, stripped of the leading '# '."""
    try:
        with path.open(encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s.startswith("# "):
                    return s[2:].strip()
    except OSError:
        pass
    return ""


def title_for(label: str, catalog: dict[str, str], path: Path) -> str:
    """CATALOG title if present, else the block's own H1, else '(no title)'."""
    return catalog.get(label) or read_h1(path) or "(no title)"


def extract_section(path: Path, header_names: tuple[str, ...]) -> list[str]:
    """Return the lines of a '## <name>' section (until the next '## ' heading).

    Matching on the header text is case-insensitive; header_names are the
    accepted heading titles (e.g. ('Connections',)).
    """
    wanted = {h.lower() for h in header_names}
    lines = path.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.startswith("## "):
            if capturing:
                break  # reached the next section
            capturing = line[3:].strip().lower() in wanted
            continue
        if capturing:
            out.append(line)
    return out


def refs_in_text(text: str) -> set[int]:
    """All block numbers referenced in a chunk of text."""
    nums: set[int] = set()
    for m in _REF_RE.finditer(text):
        for g in m.groups():
            if g:
                nums.add(int(g))
    return nums


# ---------------------------------------------------------------------------
# Focus membership (by-focus / list --focus)
#
# Heuristic (two complementary signals, unioned):
#   1) Block-header tag: a block whose body contains `Focus: **<focus>**`
#      declares itself part of that focus. This is the primary, authoritative
#      signal (used by ~71 blocks that carry the tag).
#   2) RESEARCH-STATE-<focus>.md citations: block numbers explicitly referenced
#      in the focus state file ([Block N] / [BN] / bloqueN). This recovers the
#      blocks a focus owns even when the block header predates the tag
#      convention or uses different wording.
# The union is returned as sorted labels. This is a best-effort mapping; the
# corpus does not carry a single machine-readable focus field per block.
# ---------------------------------------------------------------------------
def blocks_for_focus(focus: str) -> list[str]:
    focus_l = focus.lower()
    header_re = re.compile(r"Focus:\s*\*\*" + re.escape(focus) + r"\*\*", re.IGNORECASE)
    found: set[str] = set()

    # Signal 1: block-header Focus tag.
    for label, path in iter_block_files():
        try:
            head = path.read_text(encoding="utf-8")[:2000]
        except OSError:
            continue
        if header_re.search(head):
            found.add(label)

    # Signal 2: RESEARCH-STATE-<focus>.md citations.
    state = REPO_ROOT / f"RESEARCH-STATE-{focus}.md"
    if state.is_file():
        cited = refs_in_text(state.read_text(encoding="utf-8"))
        for n in cited:
            found.add(str(n))

    return sorted(found, key=label_sort_key)


def available_focuses() -> list[str]:
    out = []
    for p in sorted(REPO_ROOT.glob("RESEARCH-STATE-*.md")):
        out.append(p.name[len("RESEARCH-STATE-"):-len(".md")])
    return out


# ---------------------------------------------------------------------------
# Search corpus selection
# ---------------------------------------------------------------------------
def corpus_targets(scope: str) -> list[tuple[str, Path]]:
    """Return (display, path) pairs for the requested scope.

    For blocks, display is 'B<label>'; for docs/retros it is the relative path.
    """
    targets: list[tuple[str, Path]] = []
    if scope in ("blocks", "all"):
        for label, path in iter_block_files():
            targets.append((display_id(label), path))
    if scope in ("docs", "all"):
        for path in iter_dir_files(DOCS_DIR):
            targets.append((str(path.relative_to(REPO_ROOT)), path))
    if scope in ("retros", "all"):
        for path in iter_dir_files(RETROS_DIR):
            targets.append((str(path.relative_to(REPO_ROOT)), path))
    return targets


def run_search(pattern, scope: str, limit: int, catalog: dict[str, str]) -> int:
    """Shared engine for find/grep. `pattern` has a .search(str) method.

    Prints, grouped per file: a header line, then matching 'lineno: text'
    lines. `limit` caps the TOTAL number of matching lines printed.
    """
    shown = 0
    printed_any = False
    for display, path in corpus_targets(scope):
        if shown >= limit:
            break
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            continue
        matches = [(i + 1, ln) for i, ln in enumerate(lines) if pattern.search(ln)]
        if not matches:
            continue
        # Header: 'B<N> · <title>' for blocks, '<relpath> · <H1>' otherwise.
        if display.startswith("B"):
            label = display[1:]
            header = f"{display} · {title_for(label, catalog, path)}"
        else:
            header = f"{display} · {read_h1(path)}".rstrip(" ·")
        if printed_any:
            print()
        print(header)
        printed_any = True
        for lineno, text in matches:
            if shown >= limit:
                print(f"    ... (limit {limit} reached; use --limit to see more)")
                break
            print(f"  {lineno:>6}: {text.strip()}")
            shown += 1
    if not printed_any:
        print("No matches.")
        return 1
    return 0


# ---------------------------------------------------------------------------
# TF-IDF semantic ranking (lexical-semantic; stdlib pure — no torch/sklearn)
#
# Tokenization: lowercase, split on non-alphanumeric, drop tokens < 3 chars
# and a combined English+Spanish stopword set.  IDF smoothing:
#   idf(t) = log(N / (1 + df(t))) + 1
# Cosine similarity on the resulting sparse vectors.
# ---------------------------------------------------------------------------
_TFIDF_SPLIT_RE = re.compile(r"[^a-z0-9]+")

_STOPWORDS: frozenset[str] = frozenset({
    # English
    "the", "and", "for", "with", "this", "that", "are", "was", "were",
    "has", "have", "had", "not", "but", "from", "into", "its", "can",
    "will", "also", "all", "any", "one", "each", "when", "then", "than",
    "they", "them", "their", "there", "been", "being", "out", "more",
    "over", "such", "how", "use", "used", "using", "per", "via", "get",
    "set", "new", "add", "may", "see", "two", "own", "now", "well",
    # Spanish
    "que", "los", "las", "del", "por", "una", "con", "para", "como",
    "sus", "son", "sin", "mas", "hay", "ser", "est", "una",
})


def _tokenize_for_tfidf(text: str) -> list[str]:
    """Lowercase, split on non-alphanumeric, drop tokens < 3 chars and stopwords."""
    return [
        t for t in _TFIDF_SPLIT_RE.split(text.lower())
        if len(t) >= 3 and t not in _STOPWORDS
    ]


def _build_tfidf_index(
    blocks: list[tuple[str, Path]],
) -> tuple[list[tuple[str, Path, dict[str, float], float]], dict[str, float]]:
    """Build per-block TF-IDF sparse vectors.

    Returns (index, idf_table) where:
      index — list of (label, path, tfidf_sparse_dict, L2_norm)
      idf_table — {term: idf_weight} for constructing the query vector
    """
    all_tokens: list[list[str]] = []
    for _, path in blocks:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            text = ""
        all_tokens.append(_tokenize_for_tfidf(text))

    n_docs = len(blocks)

    # Document frequency.
    df: dict[str, int] = {}
    for tokens in all_tokens:
        for t in set(tokens):
            df[t] = df.get(t, 0) + 1

    # IDF with smoothing.
    idf: dict[str, float] = {
        t: math.log(n_docs / (1 + cnt)) + 1.0
        for t, cnt in df.items()
    }

    # Per-block sparse TF-IDF vector + L2 norm.
    index: list[tuple[str, Path, dict[str, float], float]] = []
    for (label, path), tokens in zip(blocks, all_tokens):
        tf: dict[str, int] = {}
        for t in tokens:
            tf[t] = tf.get(t, 0) + 1
        tfidf: dict[str, float] = {t: cnt * idf[t] for t, cnt in tf.items()}
        norm_sq = sum(v * v for v in tfidf.values())
        norm = math.sqrt(norm_sq) if norm_sq > 0 else 0.0
        index.append((label, path, tfidf, norm))

    return index, idf


def _semantic_ranked(
    query: str,
    blocks: list[tuple[str, Path]],
) -> list[tuple[float, str, Path]]:
    """Return (cosine_sim, label, path) sorted desc; skips zero-score blocks."""
    query_tokens = _tokenize_for_tfidf(query)
    if not query_tokens:
        return []

    index, idf = _build_tfidf_index(blocks)

    qtf: dict[str, int] = {}
    for t in query_tokens:
        qtf[t] = qtf.get(t, 0) + 1
    qtfidf: dict[str, float] = {t: cnt * idf.get(t, 0.0) for t, cnt in qtf.items()}
    qnorm_sq = sum(v * v for v in qtfidf.values())
    qnorm = math.sqrt(qnorm_sq) if qnorm_sq > 0 else 0.0

    if qnorm == 0.0:
        return []

    scored: list[tuple[float, str, Path]] = []
    for label, path, tfidf, norm in index:
        if norm == 0.0:
            continue
        dot = sum(qtfidf[t] * tfidf.get(t, 0.0) for t in qtfidf if t in tfidf)
        if dot == 0.0:
            continue
        sim = dot / (qnorm * norm)
        scored.append((sim, label, path))

    scored.sort(key=lambda t: -t[0])
    return scored


def _best_snippet(lines: list[str], query_terms: set[str]) -> str:
    """Return the line with the highest count of query-term substring matches."""
    best = ""
    best_count = -1
    for line in lines:
        line_lower = line.lower()
        count = sum(1 for t in query_terms if t in line_lower)
        if count > best_count:
            best_count = count
            best = line.strip()
    return best


def cmd_semantic(args) -> int:
    """Rank blocks by TF-IDF cosine similarity to the query, best first.

    Note: this is TF-IDF lexical-semantic ranking; true neural embeddings
    would need an external model/dependency (out of scope, keeps the tool
    stdlib-pure).
    """
    catalog = load_catalog()
    query_terms_set = set(textsearch.parse_query(args.query))  # for snippet
    blocks = iter_block_files()
    scored = _semantic_ranked(args.query, blocks)

    if not scored:
        print("No semantic matches.")
        print("(Note: absence of semantic matches is not proof of absence.)")
        return 1

    for sim, label, path in scored[: args.limit]:
        title = title_for(label, catalog, path)
        print(f"{display_id(label)} · {title}   (score {sim:.3f})")
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            lines = []
        snippet = _best_snippet(lines, query_terms_set)
        if snippet:
            if len(snippet) > 120:
                snippet = snippet[:117] + "..."
            print(f"  » {snippet}")

    return 0


# ---------------------------------------------------------------------------
# Command implementations
# ---------------------------------------------------------------------------
def cmd_find(args) -> int:
    """Full-text search with tokenized matching and relevance ranking.

    Tokenises *args.query* into terms so that multi-word queries match files
    where the words appear *anywhere* (not necessarily as a contiguous phrase).
    Results are sorted by relevance score (most-relevant first) before printing.

    Mode flags (--and / --or) control the file-level matching:
        --or  (default): a block is shown if ANY term is present in it.
        --and:           a block is shown only if ALL terms are present.

    Single-word queries behave identically to the original implementation.
    """
    catalog = load_catalog()
    terms = textsearch.parse_query(args.query)
    mode = "and" if getattr(args, "mode_and", False) else "or"

    if not terms:
        print("No matches.")
        return 1

    # Collect (score, display, path, matching_lines) for every matching block.
    ranked: list[tuple[int, str, Path, list[tuple[int, str]]]] = []
    for display, path in corpus_targets(args.scope):
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            continue
        text_lower = "\n".join(lines).lower()
        if not textsearch.file_matches(terms, text_lower, mode):
            continue
        s = textsearch.score(terms, text_lower)
        hits = [
            (i + 1, ln)
            for i, ln in enumerate(lines)
            if textsearch.line_hits(terms, ln.lower())
        ]
        ranked.append((s, display, path, hits))

    if not ranked:
        print("No matches.")
        return 1

    # Sort by score descending so the most-relevant blocks appear first.
    ranked.sort(key=lambda t: -t[0])

    shown = 0
    printed_any = False
    for _score, display, path, hits in ranked:
        if shown >= args.limit:
            break
        if display.startswith("B"):
            label = display[1:]
            header = f"{display} · {title_for(label, catalog, path)}"
        else:
            header = f"{display} · {read_h1(path)}".rstrip(" ·")
        if printed_any:
            print()
        print(header)
        printed_any = True
        for lineno, text in hits:
            if shown >= args.limit:
                print(f"    ... (limit {args.limit} reached; use --limit to see more)")
                break
            print(f"  {lineno:>6}: {text.strip()}")
            shown += 1

    return 0


def cmd_grep(args) -> int:
    catalog = load_catalog()
    try:
        pattern = re.compile(args.regex, re.IGNORECASE)
    except re.error as e:
        print(f"Invalid regex: {e}", file=sys.stderr)
        return 2
    return run_search(pattern, args.scope, args.limit, catalog)


def _find_block_path(n: int) -> tuple[str, Path] | None:
    """Locate a numeric block file by its number."""
    for label, path in iter_block_files():
        if label not in ("1-3", "TI") and int(label) == n:
            return label, path
    return None


def cmd_show(args) -> int:
    catalog = load_catalog()
    found = _find_block_path(args.n)
    if not found:
        print(f"Block B{args.n} not found.", file=sys.stderr)
        return 1
    label, path = found

    print(f"{display_id(label)} · {title_for(label, catalog, path)}")
    print(f"  file: {path.relative_to(REPO_ROOT)}")

    # Section outline: every ## / ### heading (H1 already printed above).
    print("\n## Outline")
    any_heading = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("### "):
            print(f"    - {line[4:].strip()}")
            any_heading = True
        elif line.startswith("## "):
            print(f"  - {line[3:].strip()}")
            any_heading = True
    if not any_heading:
        print("  (no sub-headings)")

    # Connections section verbatim.
    print("\n## Connections")
    conn = extract_section(path, ("Connections", "Conexiones"))
    conn_text = "\n".join(conn).strip()
    if conn_text:
        for line in conn_text.splitlines():
            print(f"  {line}")
    else:
        print("  (no Connections section)")
    return 0


def cmd_list(args) -> int:
    catalog = load_catalog()
    focus_set = None
    if args.focus:
        focus_set = set(blocks_for_focus(args.focus))
        if not focus_set:
            print(f"No blocks found for focus '{args.focus}'.", file=sys.stderr)
            return 1
    count = 0
    for label, path in iter_block_files():
        if focus_set is not None and label not in focus_set:
            continue
        print(f"{display_id(label)} · {title_for(label, catalog, path)}")
        count += 1
    print(f"\nTotal: {count} block(s)" + (f" in focus '{args.focus}'" if args.focus else ""))
    return 0


def _marker_components(text: str) -> list[str]:
    """All marker components in text, expanding combined [A/B] tokens."""
    comps: list[str] = []
    for m in _MARKER_TOKEN_RE.finditer(text):
        for part in m.group(1).split("/"):
            part = part.strip()
            if part:
                comps.append(part)
    return comps


def cmd_by_marker(args) -> int:
    catalog = load_catalog()
    marker = args.marker.strip().strip("[]").lower()
    rows: list[tuple[str, int, Path]] = []
    for label, path in iter_block_files():
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        cnt = sum(1 for c in _marker_components(text) if c.lower() == marker)
        if cnt:
            rows.append((label, cnt, path))
    if not rows:
        print(f"No blocks contain marker [{args.marker}].")
        return 1
    for label, cnt, path in rows:
        print(f"{display_id(label)} · {cnt:>4} · {title_for(label, catalog, path)}")
    total = sum(c for _, c, _ in rows)
    print(f"\n{len(rows)} block(s), {total} occurrence(s) of [{args.marker}].")
    return 0


def cmd_by_focus(args) -> int:
    catalog = load_catalog()
    labels = blocks_for_focus(args.focus)
    if not labels:
        avail = ", ".join(available_focuses())
        print(f"No blocks found for focus '{args.focus}'.", file=sys.stderr)
        print(f"Known focuses: {avail}", file=sys.stderr)
        return 1
    by_file = {lbl: path for lbl, path in iter_block_files()}
    for label in labels:
        path = by_file.get(label)
        title = title_for(label, catalog, path) if path else "(block file not present)"
        print(f"{display_id(label)} · {title}")
    print(f"\nTotal: {len(labels)} block(s) in focus '{args.focus}'.")
    return 0


def cmd_connections(args) -> int:
    catalog = load_catalog()
    found = _find_block_path(args.n)
    if not found:
        print(f"Block B{args.n} not found.", file=sys.stderr)
        return 1
    label, path = found
    by_file = {lbl: p for lbl, p in iter_block_files()}

    print(f"{display_id(label)} · {title_for(label, catalog, path)}")

    # Forward: references inside this block's ## Connections section.
    print("\n## Forward links (this block -> others, from its Connections section)")
    conn = "\n".join(extract_section(path, ("Connections", "Conexiones")))
    fwd = sorted(n for n in refs_in_text(conn) if n != args.n)
    if fwd:
        for n in fwd:
            p = by_file.get(str(n))
            title = title_for(str(n), catalog, p) if p else "(not in corpus)"
            print(f"  B{n} · {title}")
    else:
        print("  (none)")

    # Reverse: any block anywhere that references B<N>.
    print(f"\n## Reverse links (other blocks -> B{args.n}, whole-corpus scan)")
    rev_rows: list[tuple[str, Path]] = []
    for lbl, p in iter_block_files():
        if lbl not in ("1-3", "TI") and int(lbl) == args.n:
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except OSError:
            continue
        if args.n in refs_in_text(text):
            rev_rows.append((lbl, p))
    rev_rows.sort(key=lambda t: label_sort_key(t[0]))
    if rev_rows:
        for lbl, p in rev_rows:
            print(f"  {display_id(lbl)} · {title_for(lbl, catalog, p)}")
    else:
        print("  (none)")
    return 0


def cmd_stats(args) -> int:
    blocks = iter_block_files()
    docs = iter_dir_files(DOCS_DIR)
    retros = iter_dir_files(RETROS_DIR)

    marker_counts: dict[str, int] = {}
    with_connections = 0
    for label, path in blocks:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for c in _marker_components(text):
            marker_counts[c] = marker_counts.get(c, 0) + 1
        if extract_section(path, ("Connections", "Conexiones")):
            with_connections += 1

    print("Corpus totals")
    print(f"  blocks : {len(blocks)}")
    print(f"  docs   : {len(docs)}")
    print(f"  retros : {len(retros)}")
    print(f"  focuses: {len(available_focuses())}")
    print(f"  blocks with a Connections section: {with_connections}")

    print("\nEvidence markers (occurrences across blocks)")
    # Sort by count desc, then name asc for determinism.
    for marker in sorted(marker_counts, key=lambda m: (-marker_counts[m], m)):
        print(f"  {marker:<18} {marker_counts[marker]:>6}")
    return 0


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------
def cmd_selftest(args) -> int:  # noqa: ARG001
    """Assert core search behaviours.  Exits non-zero on the first failure.

    Ported from niagara-research (N4 kit tool): the N4 version scanned the REAL
    corpus for a term ("BStatus") known to occur in specific N4 blocks. That
    made the selftest depend on corpus content that does not exist here — a
    fresh N5 corpus has no blocks yet, and even once it does, pinning a
    selftest to one target's vocabulary is fragile. This port builds a small
    synthetic fixture corpus in a temp dir and points REPO_ROOT/CATALOG_PATH
    at it for the duration of the assertions, so the selftest is hermetic and
    passes regardless of what has actually been written into the corpus.
    """
    global REPO_ROOT, CATALOG_PATH
    errors: list[str] = []

    _orig_repo_root, _orig_catalog_path = REPO_ROOT, CATALOG_PATH
    _tmp = tempfile.TemporaryDirectory()
    try:
        tmp_root = Path(_tmp.name)
        (tmp_root / "niagara5-block1.md").write_text(
            "# Block 1: BStatus overridden\n\n"
            "Some text about a point's BStatus overridden by an operator.\n",
            encoding="utf-8",
        )
        (tmp_root / "niagara5-block2.md").write_text(
            "# Block 2: unrelated topic\n\nContent with nothing in common.\n",
            encoding="utf-8",
        )
        (tmp_root / "CATALOG.md").write_text(
            "| Block | File | Title |\n"
            "|-------|------|-------|\n"
            "| 1 | [niagara5-block1.md](niagara5-block1.md) | BStatus overridden |\n"
            "| 2 | [niagara5-block2.md](niagara5-block2.md) | unrelated topic |\n",
            encoding="utf-8",
        )
        REPO_ROOT = tmp_root
        CATALOG_PATH = tmp_root / "CATALOG.md"

        _run_selftest_assertions(errors)
    finally:
        REPO_ROOT, CATALOG_PATH = _orig_repo_root, _orig_catalog_path
        _tmp.cleanup()

    if errors:
        for e in errors:
            print(f"  FAIL  {e}", file=sys.stderr)
        return 1
    print("selftest: all assertions passed.")
    return 0


def _run_selftest_assertions(errors: list[str]) -> None:
    # --- Test 1: single-word term returns at least one block ---------------
    terms1 = textsearch.parse_query("BStatus")
    hits1 = sum(
        1 for _, path in corpus_targets("blocks")
        if textsearch.file_matches(terms1, path.read_text(encoding="utf-8").lower(), "or")
    )
    if hits1 == 0:
        errors.append("'BStatus' (single-word OR) → 0 blocks; expected > 0")
    else:
        print(f"  PASS  single-word 'BStatus' → {hits1} block(s)")

    # --- Test 2: two-word query (OR) whose words co-occur returns > 0 ------
    terms2 = textsearch.parse_query("BStatus overridden")
    hits2 = sum(
        1 for _, path in corpus_targets("blocks")
        if textsearch.file_matches(terms2, path.read_text(encoding="utf-8").lower(), "or")
    )
    if hits2 == 0:
        errors.append("'BStatus overridden' (OR) → 0 blocks; expected > 0")
    else:
        print(f"  PASS  two-word OR 'BStatus overridden' → {hits2} block(s)")

    # --- Test 3: two-word AND also returns > 0 (both words appear in B6+) --
    hits3 = sum(
        1 for _, path in corpus_targets("blocks")
        if textsearch.file_matches(terms2, path.read_text(encoding="utf-8").lower(), "and")
    )
    if hits3 == 0:
        errors.append("'BStatus overridden' (AND) → 0 blocks; expected > 0")
    else:
        print(f"  PASS  two-word AND 'BStatus overridden' → {hits3} block(s)")

    # --- Test 4: ranking — higher-scoring block comes first ----------------
    # Synthetic in-memory check (independent of corpus content).
    terms_r = textsearch.parse_query("alarm fault")
    text_high = "alarm fault alarm fault"   # both terms, 4 total occurrences
    text_low  = "alarm"                     # one term, 1 occurrence
    s_high = textsearch.score(terms_r, text_high)
    s_low  = textsearch.score(terms_r, text_low)
    if s_high <= s_low:
        errors.append(
            f"ranking: score({text_high!r}) = {s_high} should be > "
            f"score({text_low!r}) = {s_low}"
        )
    else:
        print(f"  PASS  ranking: score(high)={s_high} > score(low)={s_low}")

    # --- Test 5: semantic ranking puts a status/BStatus block in top-5 -----
    # 'point health fault override status' should surface status-related blocks.
    catalog_st = load_catalog()
    semantic5 = _semantic_ranked("point health fault override status", iter_block_files())
    top5_titles = [
        title_for(lbl, catalog_st, p).lower()
        for _, lbl, p in semantic5[:5]
    ]
    if not any("status" in t or "bstatus" in t for t in top5_titles):
        top5_ids = [display_id(lbl) for _, lbl, _ in semantic5[:5]]
        errors.append(
            f"semantic 'point health fault override status': top-5 {top5_ids} "
            f"titles {top5_titles!r} — expected one mentioning status/BStatus"
        )
    else:
        top5_ids = [display_id(lbl) for _, lbl, _ in semantic5[:5]]
        print(f"  PASS  semantic ranking 'status' query → top-5 {top5_ids}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="corpus-nav.py",
        description="Navigate the niagara-research knowledge corpus (blocks, docs, retros).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", metavar="<command>")

    def add_scope(p):
        p.add_argument("--in", dest="scope", choices=["blocks", "docs", "retros", "all"],
                       default="blocks", help="corpus subset to search (default: blocks)")
        p.add_argument("--limit", type=int, default=50,
                       help="max matching lines to print (default: 50)")

    p_find = sub.add_parser("find", help="full-text case-insensitive tokenized search with ranking")
    p_find.add_argument("query")
    add_scope(p_find)
    _mode = p_find.add_mutually_exclusive_group()
    _mode.add_argument(
        "--and", dest="mode_and", action="store_true", default=False,
        help="ALL terms must appear in a block (AND mode)"
    )
    _mode.add_argument(
        "--or", dest="mode_or", action="store_true", default=False,
        help="ANY term matches (OR mode, default)"
    )
    p_find.set_defaults(func=cmd_find)

    p_grep = sub.add_parser("grep", help="regex (re module) search")
    p_grep.add_argument("regex")
    add_scope(p_grep)
    p_grep.set_defaults(func=cmd_grep)

    p_show = sub.add_parser("show", help="H1 + outline + Connections of block B<N>")
    p_show.add_argument("n", type=int, metavar="N")
    p_show.set_defaults(func=cmd_show)

    p_list = sub.add_parser("list", help="list all blocks (from CATALOG.md)")
    p_list.add_argument("--focus", help="filter to blocks belonging to a focus")
    p_list.set_defaults(func=cmd_list)

    p_marker = sub.add_parser("by-marker", help="blocks containing an evidence marker")
    p_marker.add_argument("marker", help="e.g. INFER, CERT, CERT-hw, CERT-live")
    p_marker.set_defaults(func=cmd_by_marker)

    p_focus = sub.add_parser("by-focus", help="blocks belonging to a focus")
    p_focus.add_argument("focus")
    p_focus.set_defaults(func=cmd_by_focus)

    p_conn = sub.add_parser("connections", help="forward + reverse block links for B<N>")
    p_conn.add_argument("n", type=int, metavar="N")
    p_conn.set_defaults(func=cmd_connections)

    p_stats = sub.add_parser("stats", help="corpus totals + marker counts")
    p_stats.set_defaults(func=cmd_stats)

    p_selftest = sub.add_parser(
        "selftest", help="assert core search behaviours (exits non-zero on failure)"
    )
    p_selftest.set_defaults(func=cmd_selftest)

    p_semantic = sub.add_parser(
        "semantic",
        aliases=["rank"],
        help="rank blocks by TF-IDF cosine similarity to the query (lexical-semantic)",
    )
    p_semantic.add_argument("query", help="natural-language query string")
    p_semantic.add_argument(
        "--limit", type=int, default=15,
        help="number of top results to show (default: 15)",
    )
    p_semantic.set_defaults(func=cmd_semantic)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "command", None):
        parser.print_help()
        return 0
    return args.func(args)


if __name__ == "__main__":
    # Behave like a well-mannered CLI tool when piped into `head`, `less`, etc.
    try:
        import signal
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except (ImportError, AttributeError, ValueError):
        pass  # SIGPIPE not available on this platform
    try:
        sys.exit(main())
    except BrokenPipeError:
        sys.exit(0)
